### ISSUE TITLE
This API is temporarily unavailable. 

### ISSUE THREAD

**Issue by canwushuang** [poe-platform/fastapi_poe#101]
This API is temporarily unavailable.

**Comment by chenovopride** [comment]
fastapi_poe.client.BotError: {"allow_retry": true, "text": "This API is temporarily unavailable."} 

I'm encountering the same issue. I have tried to generate a new API key, but it's still not working.

**Comment by gyyxs88** [comment]
The same issue started occurring about 10 hours ago. Changing the API key didn't help, changing the network didn't help, and changing the operating system didn't help.

**Comment by huadasheng** [comment]
The same issue
fastapi_poe.client.BotError: {"allow_retry": true, "text": "This API is temporarily unavailable."}

**Comment by canwushuang** [comment]
2days...Nothing get from the feedback of Poe from discord.

**Comment by qingyanbaby** [comment]
the same

**Comment by TeamFan** [comment]
Maybe you can get some help in this [website](https://help.poe.com/hc/en-us/requests/new).

I have submitted a feedback.Waiting their responses.

**Comment by canwushuang** [comment]
fixed
