### ISSUE TITLE
How to make the dialog context-aware when using Python api calls?

### ISSUE THREAD

**Issue by 17Reset** [poe-platform/fastapi_poe#105]
How to set up context-aware code in the API?

**Comment by JohntheLi** [comment]
Hi, sorry for the late response. Can you clarify what you mean by context-aware code? What information are you looking for exactly?

**Comment by 17Reset** [comment]
At that time I was trying to understand how to do a question with a history, and I've found a way to do it, by the way, I hope you can update the documentation of the api calls to provide more examples, thanks.

**Comment by JohntheLi** [comment]
Thanks, closing this. Will go over the documentation and see if we can provide an example for this.
