### ISSUE TITLE
Internal server error (error_id: f518718b-78a2-4498-bba8-366ae3247773) with gpt models

### ISSUE THREAD

**Issue by liku-amare** [poe-platform/fastapi_poe#115]
I am doing an experiment on a few LLMs including GPT-4o, GPT-4, GPT-3.5, and Claude-3. I am getting this error repeatedly when I call the GPT models (all three of them). 

fastapi_poe.client.BotError: {"allow_retry": true, "text": "Internal server error (error_id: f518718b-78a2-4498-bba8-366ae3247773)"}. 

This doesn't happen for the other models (for exact same input), including Claude-3-Opus and Gemini-1.5-Pro. What could be the possible issue?

**Comment by linkedlist771** [comment]
Same error, any solutions?

**Comment by liku-amare** [comment]
> Same error, any solutions?

It worked when I reduced the size of the input.

**Comment by linkedlist771** [comment]
> > Same error, any solutions?
> 
> It worked when I reduced the size of the input.

Sory to bother again, can you share you python version and the lib version and the code? I am not sure wheather it is my code's problem.

**Comment by linkedlist771** [comment]
the same code works well tody but give the error before, it should be the poe's server error.

**Comment by liku-amare** [comment]
> > > Same error, any solutions?
> > 
> > 
> > It worked when I reduced the size of the input.
> 
> Sory to bother again, can you share you python version and the lib version and the code? I am not sure wheather it is my code's problem.

This is the function I used. The `message_prompt` is prepared by another module, then passed to this function. 
```
async def get_stream_response(bot_name, message_prompt): 
    complete_response = ""
    message_1 = ProtocolMessage(role="system", content=system_message)
    message_2 = ProtocolMessage(role="user", content=message_prompt)
    query = QueryRequest(
        query=[message_1, message_2],
        user_id="",
        conversation_id="",
        message_id="",
        version=PROTOCOL_VERSION,
        type="query"
    )

    async for partial in stream_request(
        request=query,
        bot_name=bot_name,
        api_key=api_key,
        base_url=base_url
    ):
        complete_response += partial.text
    return complete_response
```
And this is how I called the function: 
```
pred = asyncio.run(get_stream_response(model, prompt))
time.sleep(10)
```

But as you said the poe api itself has a lot of issues, it could be an issue with the api.
