### ISSUE TITLE
Don't you have wrapper for another platform beside Python.

### ISSUE THREAD

**Issue by tangible-idea** [poe-platform/fastapi_poe#33]
I am a subscriber of Poe. 
It works perfectly fine.
But don't you have a wrapper for another platform besides Python.
Or
Are there any guidelines for third-party implementation?

Is it okay to call it from client side directly?

**Comment by JelleZijlstra** [comment]
We don't currently have any pre-made implementations for other languages. However, the protocol (https://developer.poe.com/server-bots/poe-protocol-specification) is language-agnostic, and could be implemented in any language. We may provide client libraries in other languages in the future.

**Comment by tangible-idea** [comment]
<img width="629" alt="Screen Shot 2023-10-25 at 5 36 44 PM" src="https://github.com/poe-platform/fastapi_poe/assets/4496005/fff8548a-446c-4d07-afc0-d83dea72b8c7">

I was trying to follow the instructions. before implementing another wrapper in another language. but I got `internal error`
Anything I missed here? I also passed Auth with Bearer Token together.

**Comment by gpww** [comment]
> I am a subscriber of Poe. It works perfectly fine. But don't you have a wrapper for another platform besides Python. Or Are there any guidelines for third-party implementation?
> 
> Is it okay to call it from client side directly?

I just implement a c# version for Sementic Kernel. I will open source the code once I finish writing it and test it well.
