### ISSUE TITLE
Error in Poe bot: Bot request to Web-Search failed : "Internal server error"

### ISSUE THREAD

**Issue by gpww** [poe-platform/fastapi_poe#35]
Isn't Web-Search accessible? 

The code is：

`async def get_responses(api_key):
    message = ProtocolMessage(role="user", content="What's today's date?")
    async for partial in get_bot_response(messages=[message], bot_name="Web-Search", api_key=api_key):
        print(partial.text)`

and result is:

`Searching ...

<search>
current
 date

Error in Poe bot: Bot request to Web-Search failed on try 0
 BotError('{"allow_retry": true, "text": "Internal server error"}')`

**Comment by shawnWXN** [comment]
I encountered the same issue as you. 

fastapi-poe: v0.0.23
code:
```python
import asyncio
from fastapi_poe.types import ProtocolMessage
from fastapi_poe.client import get_bot_response


# Create an asynchronous function to encapsulate the async for loop
async def get_responses(api_key):
    message = ProtocolMessage(role="user", content="Hello world")
    async for partial in get_bot_response(messages=[message], bot_name="Claude-instant", api_key=api_key):
        print(partial)


# Replace <api_key> with your actual API key, ensuring it is a string.
api_key = "xxxxxxxxxxxxxxx"

# Run the event loop
# For Python 3.7 and newer
asyncio.run(get_responses(api_key))

# For Python 3.6 and older, you would typically do the following:
# loop = asyncio.get_event_loop()
# loop.run_until_complete(get_responses(api_key))
# loop.close()
```

output:
```
Error in Poe bot: Bot request to Claude-instant failed on try 0 
 BotError('{"allow_retry": true, "text": "Internal server error"}')
Traceback (most recent call last):
  File "E:\Pycharm WorkSpace\poe-demo\quick_query.py", line 18, in <module>
    asyncio.run(get_responses(api_key))
  File "C:\Users\xxx\miniconda3\envs\poe_demo\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\xxx\miniconda3\envs\poe_demo\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\Pycharm WorkSpace\poe-demo\quick_query.py", line 9, in get_responses
    async for partial in get_bot_response(messages=[message], bot_name="Claude-instant", api_key=api_key):
  File "C:\Users\xxx\miniconda3\envs\poe_demo\lib\site-packages\fastapi_poe\client.py", line 307, in stream_request
    async for message in ctx.perform_query_request(request):
  File "C:\Users\xxx\miniconda3\envs\poe_demo\lib\site-packages\fastapi_poe\client.py", line 209, in perform_query_request
    raise BotError(event.data)
fastapi_poe.client.BotError: {"allow_retry": true, "text": "Internal server error"}
Error in Poe bot: Bot request to Claude-instant failed on try 1 
 BotError('{"allow_retry": true, "text": "Internal server error"}')

Process finished with exit code 1
```

**Comment by pangzheng** [comment]
> 我遇到了和你一样的问题。
> 
> fastapi-poe：v0.0.23 代码：
> 
> ```python
> import asyncio
> from fastapi_poe.types import ProtocolMessage
> from fastapi_poe.client import get_bot_response
> 
> 
> # Create an asynchronous function to encapsulate the async for loop
> async def get_responses(api_key):
>     message = ProtocolMessage(role="user", content="Hello world")
>     async for partial in get_bot_response(messages=[message], bot_name="Claude-instant", api_key=api_key):
>         print(partial)
> 
> 
> # Replace <api_key> with your actual API key, ensuring it is a string.
> api_key = "xxxxxxxxxxxxxxx"
> 
> # Run the event loop
> # For Python 3.7 and newer
> asyncio.run(get_responses(api_key))
> 
> # For Python 3.6 and older, you would typically do the following:
> # loop = asyncio.get_event_loop()
> # loop.run_until_complete(get_responses(api_key))
> # loop.close()
> ```
> 
> 输出：
> 
> ```
> Error in Poe bot: Bot request to Claude-instant failed on try 0 
>  BotError('{"allow_retry": true, "text": "Internal server error"}')
> Traceback (most recent call last):
>   File "E:\Pycharm WorkSpace\poe-demo\quick_query.py", line 18, in <module>
>     asyncio.run(get_responses(api_key))
>   File "C:\Users\xxx\miniconda3\envs\poe_demo\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\xxx\miniconda3\envs\poe_demo\lib\asyncio\base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "E:\Pycharm WorkSpace\poe-demo\quick_query.py", line 9, in get_responses
>     async for partial in get_bot_response(messages=[message], bot_name="Claude-instant", api_key=api_key):
>   File "C:\Users\xxx\miniconda3\envs\poe_demo\lib\site-packages\fastapi_poe\client.py", line 307, in stream_request
>     async for message in ctx.perform_query_request(request):
>   File "C:\Users\xxx\miniconda3\envs\poe_demo\lib\site-packages\fastapi_poe\client.py", line 209, in perform_query_request
>     raise BotError(event.data)
> fastapi_poe.client.BotError: {"allow_retry": true, "text": "Internal server error"}
> Error in Poe bot: Bot request to Claude-instant failed on try 1 
>  BotError('{"allow_retry": true, "text": "Internal server error"}')
> 
> Process finished with exit code 1
> ```

API key is incorrect

**Comment by shawnWXN** [comment]
But when I change the name of the robot to "ChatGPT", it works fine.
但是我将机器人名字改成ChatGPT，它就是正常的。

**Comment by krisyang1125** [comment]
Seems like the issue is resolved, can you try again to see it is the case for you?
