### ISSUE TITLE
how to get message id with Api key

### ISSUE THREAD

**Issue by xuantoan0406** [poe-platform/fastapi_poe#37]
I use an API key with  get_bot_response (), how can I continue the context of the bot I created? Thank you !
![Screenshot from 2023-12-04 18-03-06](https://github.com/poe-platform/fastapi_poe/assets/60731605/40952482-86a3-4b8b-8df5-d0cea44d7093)

**Comment by xuantoan0406** [comment]
@JelleZijlstra Can you help me? ..thank you !

**Comment by anmolsingh95** [comment]
Sorry, can you please explain what you mean by "continue the context of the bot I created"?

**Comment by anmolsingh95** [comment]
Closing this issue for now, but for posterity the API is meant to be "state-less" and you need to manage the history on your side.
