### ISSUE TITLE
How to Allow URLs and Attachments to my Bot

### ISSUE THREAD

**Issue by abdfnx** [poe-platform/fastapi_poe#6]
Hi @JelleZijlstra, How I can use the message attachments like URLs or files to my code ?

**Comment by JelleZijlstra** [comment]
For sending files to the bot, I added an extension to  the protocol recently: https://github.com/poe-platform/documentation/commit/d67fb15919a527aed99f057dc13613eec683da49. However, it is not implemented on our side yet, I'm hoping to do that soon.

**Comment by abdfnx** [comment]
> For sending files to the bot, I added an extension to the protocol recently: [poe-platform/documentation@d67fb15](https://github.com/poe-platform/documentation/commit/d67fb15919a527aed99f057dc13613eec683da49). However, it is not implemented on our side yet, I'm hoping to do that soon.

and what about URLs ?

**Comment by JelleZijlstra** [comment]
Users can just type in URLs in the markdown input, no special support needed.

**Comment by abdfnx** [comment]
![Web capture_6-8-2023_172825_poe com](https://github.com/poe-platform/fastapi_poe/assets/64256993/28bfb12d-e90f-4601-8596-810a89ed1d13)

Look

**Comment by JelleZijlstra** [comment]
That's something you should be able to do in your own bot. In your code, you can recognize that there is a URL and fetch the data from the Internet.

**Comment by abdfnx** [comment]
Can you give me an example code ?

**Comment by abdfnx** [comment]
![Web capture_6-8-2023_17388_poe com](https://github.com/poe-platform/fastapi_poe/assets/64256993/e0f2b87d-2edc-44f7-ae4a-8429ab5b9c2c)

I want it to be like this

**Comment by abdfnx** [comment]
Please @JelleZijlstra

**Comment by abdfnx** [comment]
OK @JelleZijlstra

**Comment by JelleZijlstra** [comment]
Sorry I can't give example code right now. We may add support for URL fetching to API bots on our side in the future.

**Comment by qingyanbaby** [comment]
> Sorry I can't give example code right now. We may add support for URL fetching to API bots on our side in the future.

Is it supported now? @JelleZijlstra
